### ISSUE TITLE
How to use the Actor API in the browser

### ISSUE THREAD

**Issue by dkhan11** [JoeHegarty/ratatoskr#4]
Hi,

Is there a simple way to use the client API directly from the browser? 

Thanks,
DD.

**Comment by JoeHegarty** [comment]
There isn't currently a way to run Ratatoskr in a browser. What is your use case?
In order to achieve this you'd need to expose your actors via some kind of public API (REST/Websockets etc) and call them via that.

In the long term I do plan to offer a client library, but I've been very busy recently and haven't had a lot of chance to continue working on the framework. I hope that will change in the near future.

**Comment by dkhan11** [comment]
Ok, got it.
Thank you!
DD.
